item {
  id: 1
  name: 'ma_1W'
}

item {
  id: 2
  name: 'ma_2W'
}

item {
  id: 3
  name: 'ma_3W'
}

item {
  id: 4
  name: 'ma_4W'
}

item {
  id: 5
  name: 'ma_5W'
}

item {
  id: 6
  name: 'ma_6W'
}

item {
  id: 7
  name: 'ma_7W'
}

item {
  id: 8
  name: 'ma_8W'
}

item {
  id: 9
  name: 'ma_9W'
}

item {
  id: 10
  name: 'ma_EAST'
}

item {
  id: 11
  name: 'ma_SOUTH'
}

item {
  id: 12
  name: 'ma_WEST'
}

item {
  id: 13
  name: 'ma_NORTH'
}

item {
  id: 14
  name: 'ma_CHONG'
}

item {
  id: 15
  name: 'ma_FA'
}

item {
  id: 16
  name: 'ma_BAI'
}